-- Table that need to be created in the 
CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_SYC (
            SYC_ID INT NOT NULL AUTO_INCREMENT,
            TOKEN_ID VARCHAR (255),
            ACCESS_TOKEN VARCHAR(255),
            REFRESH_TOKEN VARCHAR(255),
            CONSUMER_KEY_ID INTEGER,
            AUTHZ_USER VARCHAR (100),
            TENANT_ID INTEGER,
            USER_DOMAIN VARCHAR(50),
            USER_TYPE VARCHAR (25),
            GRANT_TYPE VARCHAR (50),
            TIME_CREATED TIMESTAMP DEFAULT 0,
            REFRESH_TOKEN_TIME_CREATED TIMESTAMP DEFAULT 0,
            VALIDITY_PERIOD BIGINT,
            REFRESH_TOKEN_VALIDITY_PERIOD BIGINT,
            TOKEN_SCOPE_HASH VARCHAR(32),
            TOKEN_STATE VARCHAR(25) DEFAULT 'ACTIVE',
            TOKEN_STATE_ID VARCHAR (128) DEFAULT 'NONE',
            SUBJECT_IDENTIFIER VARCHAR(255),
            IS_SYCH VARCHAR (10),
            PRIMARY KEY (TOKEN_ID),
            CONSTRAINT CON_APP_KEY UNIQUE (CONSUMER_KEY_ID,AUTHZ_USER,TENANT_ID,USER_DOMAIN,USER_TYPE,TOKEN_SCOPE_HASH,
                                           TOKEN_STATE,TOKEN_STATE_ID)
)ENGINE INNODB;


--Creating the indexes
CREATE INDEX IDX_AT_CK_AU_SYC ON IDN_OAUTH2_ACCESS_TOKEN_SYC(CONSUMER_KEY_ID, AUTHZ_USER, TOKEN_STATE, USER_TYPE);

CREATE INDEX IDX_TC_SYC ON IDN_OAUTH2_ACCESS_TOKEN_SYC(TIME_CREATED);

CREATE INDEX IDX_AT_SYC ON IDN_OAUTH2_ACCESS_TOKEN_SYC(ACCESS_TOKEN);


CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_SCOPE_SYC (
            SYC_ID INT NOT NULL AUTO_INCREMENT,
            TOKEN_ID VARCHAR (255),
            TOKEN_SCOPE VARCHAR (60),
            TENANT_ID INTEGER DEFAULT -1,
            IS_SYCH VARCHAR (10),
            PRIMARY KEY (TOKEN_ID, TOKEN_SCOPE)
)ENGINE INNODB;


CREATE TRIGGER ADD_SYC_TOKEN
BEFORE INSERT ON `IDN_OAUTH2_ACCESS_TOKEN`

FOR EACH ROW BEGIN
	INSERT INTO IDN_OAUTH2_ACCESS_TOKEN_SYC (
		TOKEN_ID,ACCESS_TOKEN,REFRESH_TOKEN,
        ONSUMER_KEY_ID,AUTHZ_USER,TENANT_ID,
        USER_DOMAIN,USER_TYPE,GRANT_TYPE,
        TIME_CREATED,REFRESH_TOKEN_TIME_CREATED,
        VALIDITY_PERIOD,REFRESH_TOKEN_VALIDITY_PERIOD,
        TOKEN_SCOPE_HASH, TOKEN_STATE,TOKEN_STATE_ID, 
        SUBJECT_IDENTIFIER,IS_SYCH
	) VALUES(
		NEW.TOKEN_ID, NEW.ACCESS_TOKEN, NEW.REFRESH_TOKEN,
        NEW.CONSUMER_KEY_ID,NEW.AUTHZ_USER, NEW.TENANT_ID,
        NEW.USER_DOMAIN, NEW.USER_TYPE, NEW.GRANT_TYPE,
        NEW.TIME_CREATED,NEW.REFRESH_TOKEN_TIME_CREATED,
        NEW.VALIDITY_PERIOD, NEW.REFRESH_TOKEN_VALIDITY_PERIOD,
        NEW.TOKEN_SCOPE_HASH, NEW.TOKEN_STATE,TOKEN_STATE_ID, 
        NEW.SUBJECT_IDENTIFIER,"NOTSYC"
	);