USE IS_apimgtdb;


SET SESSION sql_mode = '';

SET SESSION SQL_MODE='ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS IDN_OAUTH2_ACCESS_TOKEN_SYNC;

CREATE TABLE `IDN_OAUTH2_ACCESS_TOKEN_SYNC` (
`SYC_ID` INT NOT NULL AUTO_INCREMENT,
  `TOKEN_ID` varchar(255) NOT NULL,
  `ACCESS_TOKEN` varchar(999) DEFAULT NULL,
  `REFRESH_TOKEN` varchar(255) DEFAULT NULL,
  `CONSUMER_KEY_ID` int(11) DEFAULT NULL,
  `AUTHZ_USER` varchar(100) DEFAULT NULL,
  `TENANT_ID` int(11) DEFAULT NULL,
  `USER_DOMAIN` varchar(50) DEFAULT NULL,
  `USER_TYPE` varchar(25) DEFAULT NULL,
  `GRANT_TYPE` varchar(50) DEFAULT NULL,
  `TIME_CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `REFRESH_TOKEN_TIME_CREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `VALIDITY_PERIOD` bigint(20) DEFAULT NULL,
  `REFRESH_TOKEN_VALIDITY_PERIOD` bigint(20) DEFAULT NULL,
  `TOKEN_SCOPE_HASH` varchar(999) DEFAULT NULL,
  `TOKEN_STATE` varchar(25) DEFAULT 'ACTIVE',
  `TOKEN_STATE_ID` varchar(128) DEFAULT 'NONE',
  `SUBJECT_IDENTIFIER` varchar(255) DEFAULT NULL,
  TRASACTION VARCHAR (10),
   IS_SYCH VARCHAR (10),
  PRIMARY KEY (`SYC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TRIGGER IF EXISTS SYC_TOKEN_INSERT_TRIGR;

DELIMITER //

CREATE TRIGGER SYC_TOKEN_INSERT_TRIGR 
BEFORE INSERT ON IDN_OAUTH2_ACCESS_TOKEN
FOR EACH ROW BEGIN INSERT
			INTO
				IDN_OAUTH2_ACCESS_TOKEN_SYNC(
					TOKEN_ID,
					ACCESS_TOKEN,
					REFRESH_TOKEN,
					CONSUMER_KEY_ID,
					AUTHZ_USER,
					TENANT_ID,
					USER_DOMAIN,
					USER_TYPE,
					GRANT_TYPE,
					TIME_CREATED,
					REFRESH_TOKEN_TIME_CREATED,
					VALIDITY_PERIOD,
					REFRESH_TOKEN_VALIDITY_PERIOD,
					TOKEN_SCOPE_HASH,
					TOKEN_STATE,
					TOKEN_STATE_ID,
					SUBJECT_IDENTIFIER,
					TRASACTION,
					IS_SYCH
				)
			VALUES(
				NEW.TOKEN_ID,
				NEW.ACCESS_TOKEN,
				NEW.REFRESH_TOKEN,
				NEW.CONSUMER_KEY_ID,
				NEW.AUTHZ_USER,
				NEW.TENANT_ID,
				NEW.USER_DOMAIN,
				NEW.USER_TYPE,
				NEW.GRANT_TYPE,
				NEW.TIME_CREATED,
				NEW.REFRESH_TOKEN_TIME_CREATED,
				NEW.VALIDITY_PERIOD,
				NEW.REFRESH_TOKEN_VALIDITY_PERIOD,
				NEW.TOKEN_SCOPE_HASH,
				NEW.TOKEN_STATE,
				TOKEN_STATE_ID,
				NEW.SUBJECT_IDENTIFIER,
				"INSERT",
				"NOTSYC"
			);
END//

DELIMITER ;

DROP TRIGGER IF EXISTS SYC_TOKEN_UPDATE_TRIGR;

DELIMITER //

CREATE TRIGGER SYC_TOKEN_UPDATE_TRIGR
BEFORE UPDATE
   ON IDN_OAUTH2_ACCESS_TOKEN FOR EACH ROW

BEGIN

   INSERT
			INTO
				IDN_OAUTH2_ACCESS_TOKEN_SYNC(
					TOKEN_ID,
					ACCESS_TOKEN,
					REFRESH_TOKEN,
					CONSUMER_KEY_ID,
					AUTHZ_USER,
					TENANT_ID,
					USER_DOMAIN,
					USER_TYPE,
					GRANT_TYPE,
					TIME_CREATED,
					REFRESH_TOKEN_TIME_CREATED,
					VALIDITY_PERIOD,
					REFRESH_TOKEN_VALIDITY_PERIOD,
					TOKEN_SCOPE_HASH,
					TOKEN_STATE,
					TOKEN_STATE_ID,
					SUBJECT_IDENTIFIER,
					TRASACTION,
					IS_SYCH
				)
			VALUES(
				NEW.TOKEN_ID,
				NEW.ACCESS_TOKEN,
				NEW.REFRESH_TOKEN,
				NEW.CONSUMER_KEY_ID,
				NEW.AUTHZ_USER,
				NEW.TENANT_ID,
				NEW.USER_DOMAIN,
				NEW.USER_TYPE,
				NEW.GRANT_TYPE,
				NEW.TIME_CREATED,
				NEW.REFRESH_TOKEN_TIME_CREATED,
				NEW.VALIDITY_PERIOD,
				NEW.REFRESH_TOKEN_VALIDITY_PERIOD,
				NEW.TOKEN_SCOPE_HASH,
				NEW.TOKEN_STATE,
				TOKEN_STATE_ID,
				NEW.SUBJECT_IDENTIFIER,
				"UPDATE",
				"NOTSYC"
			);
END; //

DELIMITER ;


DROP TABLE IF EXISTS IDN_OAUTH2_ACCESS_TOKEN_SCOPE_SYNC;

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_SCOPE_SYNC (
            SYC_ID INT NOT NULL AUTO_INCREMENT,
            TOKEN_ID VARCHAR (255),
            TOKEN_SCOPE VARCHAR (60),
            TENANT_ID INTEGER DEFAULT -1,
            IS_SYCH VARCHAR (10),
            PRIMARY KEY (SYC_ID)
)ENGINE INNODB;





select * from IDN_OAUTH2_ACCESS_TOKEN;

INSERT INTO IS_apimgtdb.IDN_OAUTH2_ACCESS_TOKEN
(TOKEN_ID, ACCESS_TOKEN, REFRESH_TOKEN, CONSUMER_KEY_ID, AUTHZ_USER, TENANT_ID, USER_DOMAIN, USER_TYPE, GRANT_TYPE, TIME_CREATED, REFRESH_TOKEN_TIME_CREATED, VALIDITY_PERIOD, REFRESH_TOKEN_VALIDITY_PERIOD, TOKEN_SCOPE_HASH, TOKEN_STATE, TOKEN_STATE_ID, SUBJECT_IDENTIFIER)
VALUES('213123213-f34xd342d', '231231-2332312d313', '', 1, '', 0, '', '', '', '0000-00-00 00:00:01', '0000-00-00 00:00:03', 0, 0, '32f242d3df42', 'ACTIVE', 'NONE', '');

UPDATE IS_apimgtdb.IDN_OAUTH2_ACCESS_TOKEN
SET ACCESS_TOKEN='231231', REFRESH_TOKEN='33243242'
WHERE TOKEN_ID='213123213-34342';


select * from IDN_OAUTH_CONSUMER_APPS

select * from IDN_OAUTH2_ACCESS_TOKEN_SYNC;
