DELIMITER //

CREATE TABLE IF NOT EXISTS `IDN_OAUTH2_ACCESS_TOKEN_SYNCD_ID` (
`SYC_ID` INT
) ENGINE=InnoDB DEFAULT CHARSET=latin1; //

CREATE TABLE IF NOT EXISTS `IDN_OAUTH2_ACCESS_TOKEN_SCOPE_SYNCD_ID` (
`SYC_ID` INT
) ENGINE=InnoDB DEFAULT CHARSET=latin1; //

CREATE TABLE IF NOT EXISTS `IDN_OAUTH2_AUTHORIZATION_CODE_SYNCD_ID` (
`SYC_ID` INT
) ENGINE=InnoDB DEFAULT CHARSET=latin1; //


DELIMITER ;